---
- name: mssql server database backup
  hosts: cobra
  vars: 
    - database_name: cobra_main
    - dbserver_name: ATMF-COBRA-01
  roles:
    - mssql_backup
- name: mssql server database backup
  hosts: cobra
  vars: 
    - database_name: CobraDemoData
    - dbserver_name: ATMF-COBRA-01
  roles:
    - mssql_backup
