---

- name: Installing jdk8 using chocolatey module
  win_chocolatey:
    name: jdk8

- name: Get actual PATH
  raw: $ENV:PATH
  register: path_out

- name: Add java to path to environment variable
  raw: SETX /M PATH "$ENV:PATH;C:\Program Files\Java\jdk1.8.0_102\bin"
  when: path_out.stdout.find('jre') == -1

- name:  Create temp folder
  win_file:
     path: c:\\temp
     state: directory

- name: Download Nexus from Sonatype website
  win_get_url:
   url: 'https://download.sonatype.com/downloads/products/nexus/nexus-professional-bundle-latest.zip'
   dest: 'c:/temp/nexus-professional.zip'


- name: Unzip Nexus
  win_unzip:
    src: "c:/temp/nexus-professional.zip"
    dest: "c:/Nexus_Repo/"
    creates: "c:/Nexus_Repo"

- name: Start Nexus service on 8081 port
  win_service:
   name: nexus
   start_mode: auto
   state: started
