---

- name: Download java executable file from ftp server
  win_get_url: 
    url: 'http://52.187.62.107/downloads/jdk-8u101-windows-x64(1).exe'
    dest: 'C:\\jdk-8u101-windows-x64(1).exe'

- name: Copy the java configuration file
  win_copy: src=myconf.cfg dest='C:\\myconf.cfg'

- name: Installation of java using executable file
  raw: 'C:/jdk-8u101-windows-x64(1).exe INSTALLCFG=C:/myconf.cfg'

- name: Get actual PATH
  raw: $ENV:PATH
  register: path_out
  
- name: Add java to path 
  raw: SETX /M PATH "$ENV:PATH;{{java_path}}"
  when: path_out.stdout.find('jre') == -1
  
