---

- name: Download the  mRemote MG installer
  win_get_url:
      url: 'http://mremoteng.software.informer.com/download/'
      dest: 'C:\temp\mremoteng-installer-1.72.exe'

- name: Install MSI
  raw:
      path: 'C:\temp\mremoteng-installer-1.72.exe'
      state: present
      extra_args: '/S'
