---
- name: mssql server database restore
  hosts: cobra2
  vars: 
    - database_name: cobra_main
    - dbserver_name: ATMF-COBRA-02
  roles:
    - mssql_restore
- name: mssql server database restore
  hosts: cobra2
  vars: 
    - database_name: CobraDemoData
    - dbserver_name: ATMF-COBRA-02
  roles:
    - mssql_restore
