---

- name: Download the  mRemote MG installer
      win_get_url:
        url: 'https://github.com/mickem/nscp/releases/download/0.5.0.62/NSCP-0.5.0.62-x64.msi/'
        dest: 'C:\Users\vagrant\Downloads\NSCP-0.5.0.62-x64.msi'

    - name: Install MSI
      raw:
        path: 'C:\Users\vagrant\Downloads\NSCP-0.5.0.62-x64.msi'
        state: present
        extra_args: '/qn'